### ISSUE TITLE
Help solve the problem with Plex Tuner Service

### ISSUE THREAD

**Issue by free-14** [uglymagoo/plexmediaserver-installer#26]
service plexmediaserver status : /usr/lib/plexmediaserver/Plex Tuner Service: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

If you take another Plex Tuner Service file (for example from ubuntu amd64) then Plex starts working. What is the problem?

**Comment by uglymagoo** [comment]
The first error only tells you, that the DVR binary is not working on your device. Everything else should still work OK. 

Taking the Play Tuner Service from an amd64 build just does nothing. The amd64 binaries do not work on your ARMv7 device, of course :) 

I suppose you just were a little impatient. Without any intervention, you would have been able to access the web frontend eventually. The first start takes some time.

The Tuner service is a know problem on some ARMv7 devices at the very low end. DVR works very well on the RPi 2 and 3 for example. There is no need to "fix" this problem, because nobody is using Plex DVR on the problematic ARMv7 devices :)

**Comment by free-14** [comment]
I have khadas vim2 ARMv8. I'll wait for a new release. And I'll try to wait after the installation (upgrade). If the first start is long. )

**Comment by uglymagoo** [comment]
The generic Linux support of this device appears to be ... difficult ... . Android appears to be the main target OS. Please understand, that I cannot fix the broken Linux support. If you are interested in a stable Plex operation, please use a device whose target audience is Linux, e.g. RPi 2/3.
