### ISSUE TITLE
Users unable to change Environment

### ISSUE THREAD

**Issue by Generator** [uglymagoo/plexmediaserver-installer#28]
## Expected Behavior
Changing configuration settings on `/etc/default/plexmediaserver` changes the default _Environment_ settings

## Current Behavior
`/etc/default/plexmediaserver` is an useless file, `plexmediaserver.service` have is own _Environment_ variables and `/etc/default/plexmediaserver` isn't sourced

## Possible Solution
Use `EnvironmentFile=/etc/default/plexmediaserver` instead of `Environment=`

Example on Archlinux/AUR:
[plexmediaserver.service](https://aur.archlinux.org/cgit/aur.git/tree/plexmediaserver.service?h=plex-media-server)
[/etc/conf.d/plexmediaserver](https://aur.archlinux.org/cgit/aur.git/tree/plexmediaserver.conf.d?h=plex-media-server)

## Context
Trying to set `PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR` on a different location (external HDD). 
PS: I know i can't set this on `plexmediaserver.service` but will revert to default on package update, and isn't an user config

**Comment by uglymagoo** [comment]
Thanks for your input. I am totally aware of this better solution. However, my package is in line with the official PMS Debian package, that's why `/etc/default/plexmediaserver` is not sourced. Thus, all official Linux Plex support documents and forum posts also apply to this package.

Upstream plex chooses another solution to your problem. Please read: https://forums.plex.tv/t/linux-tips/276247/3
